# Most actions on github are either docker actions, or only for linux.
name: Upload BF S3
description: Uploads the file to the BF S3 server
inputs:
  file:
    description: 'The file to upload'
    required: true
  destination-filename:
    description: 'Target filename in s3'
    required: true
    default: ''
  s3-host:
    description: 'Server endpoint'
    required: true
    default: 's4.bitfocus.io'
  s3-bucket:
    description: 'Bucket to upload to'
    required: true
    default: ''
  s3-access-key:
    description: 'Access Key'
    required: true
    default: ''
  s3-secret-key:
    description: 'Secret Key'
    required: true
    default: ''
  run-id:
    description: 'The job id'
    required: true
outputs:
  url:
    description: "URL to uploaded file"
    value: ${{ steps.upload.outputs.url }}

runs:
  using: 'composite'
  steps:
    - name: Download minio client
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        wget -q https://dl.min.io/client/mc/release/linux-amd64/mc
        chmod +x mc
    - name: Download minio client
      if: ${{ runner.os == 'Windows' }}
      shell: pwsh
      run: |
        $ProgressPreference = 'SilentlyContinue'
        Invoke-WebRequest -Uri "https://dl.minio.io/client/mc/release/windows-amd64/mc.exe" -OutFile "./mc"
    - name: Download minio client
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        wget -q https://dl.min.io/client/mc/release/darwin-amd64/mc
        chmod +x mc
    - name: Upload
      id: upload
      shell: bash
      run: |
        echo Upload file to https://${{ inputs.s3-host }}/${{ inputs.s3-bucket }}${{ inputs.destination-filename }}
        export HOME="$(pwd)" MC_CONFIG_DIR="$(pwd)"
        ./mc alias set remote/ https://${{ inputs.s3-host }} ${{ inputs.s3-access-key }} ${{ inputs.s3-secret-key }}
        ./mc cp "${{ inputs.file }}" "remote/${{ inputs.s3-bucket }}/${{ inputs.destination-filename }}"
        echo "url=https://${{ inputs.s3-host }}/${{ inputs.s3-bucket }}/${{ inputs.destination-filename }}" >> $GITHUB_OUTPUT